export const GET_PRODUCT = 'GET_PRODUCT'
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_FAIL = 'GET_PRODUCT_FAIL'
export const SELECT_TRADEMARK_SERIES = 'SELECT_TRADEMARK_SERIES'

export const ADD_CART = 'ADD_CART'
export const ADD_CART_SUCCESS = 'ADD_CART_SUCCESS'
export const ADD_CART_FAIL = 'ADD_CART_FAIL'

