export const SHOW_LOADING = 'GLOBAL_SHOW_LOADING';
export const HIDE_LOADING = 'GLOBAL_HIDE_LOADING';

export const USER_TABLE_TOGGLE = 'USER_TABLE_TOGGLE'

export const LOGIN_PAGE = 'LOGIN_PAGE'
export const SIGNIN_PAGE = 'SIGNIN_PAGE'

export const CART_TABLE = 'CART_TABLE'
