export const GET_LIST_USER = 'GET_LIST_USER';
export const GET_LIST_USER_SUCCESS = 'GET_LIST_USER_SUCCESS';
export const GET_LIST_USER_FAILED = 'GET_LIST_USER_FAILED';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';

export const CHANGE_USER_LOCAL_STORAGE = 'CHANGE_USER_LOCAL_STORAGE';

